version: '27.4.0'

services:
  b-hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:


